### ISSUE TITLE
Update model tester based on Qt changes

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#221]
It looks like the Qt modeltester had [some changes](https://github.com/qt/qtbase/commits/5.11/src/testlib/qabstractitemmodeltester.cpp) (and a [bigger refactoring](https://github.com/qt/qtbase/commit/b3e4be2d8b9debf217657436139da0152f6f8797#diff-227bd803a8cca931ce30cdfbe060dd0e)) recently. We should probably try to adopt those.

This also means links to the old `modeltester.cpp` are invalid and need updating.

**Comment by nicoddemus** [comment]
Thanks for the heads up @The-Compiler!

**Comment by The-Compiler** [comment]
Opened a PR for this, but noticed after those changes that at least PyQt5 actually exposes the new QAbstractItemModelTester from Qt!

First prototype:

```diff
diff --git a/pytestqt/logging.py b/pytestqt/logging.py
index 0e8989c..c99ee35 100644
--- a/pytestqt/logging.py
+++ b/pytestqt/logging.py
@@ -182,6 +182,8 @@ class _QtMessageCapture(object):
         Method to be installed using qInstallMessageHandler (Qt5),
         stores each message into the `_records` attribute.
         """
+        if context.category == 'qt.modeltest':
+            pytest.fail(message)
         self._append_new_record(msg_type, message, context=context)
 
     @property
diff --git a/pytestqt/modeltest.py b/pytestqt/modeltest.py
index 2d7a095..f5dcb0b 100644
--- a/pytestqt/modeltest.py
+++ b/pytestqt/modeltest.py
@@ -87,6 +87,17 @@ class ModelTester:
         Whenever anything happens recheck everything.
         """
         assert model is not None
+        try:
+            tester = qt_api.QtTest.QAbstractItemModelTester(
+                model,
+                qt_api.QtTest.QAbstractItemModelTester.FailureReportingMode.Warning,
+            )
+        except AttributeError:
+            self._debug("Using Python tester")
+        else:
+            self._debug("Using Qt tester")
+            return
+
         self._model = model
         self._fetching_more = False
         self._insert = []
```

The problem is that we can't raise an `AssertionError` on failures, so most stuff in `test_modeltester.py` fails. Didn't have a good idea to make it pass in both scenarios yet, and not sure if I want to follow this further. With that, the output also looks suboptimal at the moment:

```
_____________________________________________________________________________________________________________________________________________________________________________________ test_invalid_parent _____________________________________________________________________________________________________________________________________________________________________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Inconsistent parent() implementation detected:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed:     index= QModelIndex(0,0,0x55be250a1c80,Model(0x55be24a5ef40)) exp. parent= QModelIndex(0,0,0x55be25097ba0,Model(0x55be24a5ef40)) act. parent= QModelIndex(-1,-1,0x0,QObject(0x0))
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed:     row= 0 col= 0 depth= 2
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed:     data for child "bar"
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed:     data for parent "bar"
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/pytestqt/logging.py", line 186, in _handle_with_context
    pytest.fail(message)
  File "/home/florian/proj/pytest-qt/.tox/py37-pyqt5/lib/python3.7/site-packages/_pytest/outcomes.py", line 104, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: FAIL! Compared values are not the same:
   Actual (model->parent(index)) 
   Expected (parent) 
   (qabstractitemmodeltester.cpp:559)
```

**Comment by The-Compiler** [comment]
Thinking some more about this, I think being able to use the Qt model tester instead really has some value even if it means uglier reports. Here's what I'd propose:

- Use the Qt tester if available
- Find out whether we can get somewhat nice output somehow (either with some adjustments in `logging.py`, or maybe by installing a different message handler while the model tester is running).
- Add a `force_python=True` or so to `qtmodeltester.check` and use that for the existing tests
- Only write very basic tests for the Qt modeltester (because we don't need to test the checks themselves) using `testdir` and `fnmatch_lines`
- Maybe add a `--qt-force-python-modeltester` commandline argument which can be used to force the Python implementation easily so there are nicer outputs on failures.

What do you think?

**Comment by nicoddemus** [comment]
> Find out whether we can get somewhat nice output somehow (either with some adjustments in logging.py, or maybe by installing a different message handler while the model tester is running).

I would investigate this, it seems we can [latch](https://doc.qt.io/qt-5/qabstractitemmodeltester.html#FailureReportingMode-enum) into the QtTest logging system, although I don't know how to do it. It seems it is a different mechanism than what qt logging system uses, so it wouldn't be captured by logging and could be better handled. 

So that I understand, the error message you posted above is what a user sees themselves when they use the `qmodeltester` on their own models, right?

In the end this is just for Qt5 right? Then unfortunately it means that we can't use only the C++ implementation without breaking the API for the other implementations, meaning we will need to keep the Python implementation anyway, so in the end it will only increase our maintenance in the end. Then perhaps not using it at all would be the sensible approach? Not sure though, I trust your instincts here because you are a heavy user of model checker, I don't think I've ever used it very much. 😅

**Comment by The-Compiler** [comment]
Setting it to `QtTest` is intended for Qt's own test framework (it uses `QtTest::qCompare` and `QtTest::qVerify` which don't seem to do much when not running with QtTest).

Yeah, that error above would be what they see, though I think it could be made a bit nicer by just relying on the warning logs and making sure we always fail tests which have warnings from `qt.modeltest`:

```
None:None:0:
    QtWarningMsg: Inconsistent parent() implementation detected:
None:None:0:
    QtWarningMsg:     index= QModelIndex(0,0,0x560f412a7d90,Model(0x560f412c6a70)) exp. parent= QModelIndex(0,0,0x560f4127f830,Model(0x560f412c6a70)) act. parent= QModelIndex(-1,-1,0x0,QObject(0x0))
None:None:0:
    QtWarningMsg:     row= 0 col= 0 depth= 2
None:None:0:
    QtWarningMsg:     data for child "bar"
None:None:0:
    QtWarningMsg:     data for parent "bar"
```

(Maybe we should always hide the `None:None:0:` location if it's unknown? Doesn't seem very useful in any case.)

Indeed we'd need to keep the Python implementation for now. The nice thing about the C++ implementation is that it can test some things we can't (because they're private in the model classes).

I think it'd be worth it, and it shouldn't be too much work to get it running. I might try getting something finished enough for a PR after #238, I should still have some time on my hands tomorrow :laughing:

**Comment by nicoddemus** [comment]
Hehehe OK, thanks!
