### ISSUE TITLE
WebEnginePage not closed by qtbot

### ISSUE THREAD

**Issue by bnavigator** [pytest-dev/pytest-qt#319]
Hi,

I am still trying to fix the [spyder-notebook](https://github.com/spyder-ide/spyder-notebook) package for openSUSE. (Most) tests pass, but at the end there is a segfault. E.g. here:

```
abuild@greinerT450s:~/rpmbuild/BUILD/spyder-notebook-0.3.0> pytest -x spyder_notebook/widgets/tests/test_notebooktabwidget.py 
========================================================== test session starts ==========================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
PyQt5 5.15.0 -- Qt runtime 5.15.1 -- Qt compiled 5.15.1
rootdir: /home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.0
plugins: qt-3.3.0, xvfb-2.0.0, mock-3.1.1, flaky-3.7.0
collected 6 items                                                                                                                       

spyder_notebook/widgets/tests/test_notebooktabwidget.py ......                                                                    [100%]

=========================================================== warnings summary ============================================================
/usr/lib/python3.8/site-packages/spyder/utils/programs.py:16
  /usr/lib/python3.8/site-packages/spyder/utils/programs.py:16: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

/usr/lib/python3.8/site-packages/notebook/notebookapp.py:50
  /usr/lib/python3.8/site-packages/notebook/notebookapp.py:50: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
    ioloop.install()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================================== 6 passed, 2 warnings in 1.07s =====================================================
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
Fatal Python error: Segmentation fault

Current thread 0x00007f4b84231740 (most recent call first):
<no Python frame>
Segmentation fault (core dumped)
abuild@greinerT450s:~/rpmbuild/BUILD/spyder-notebook-0.3.0>
```
from the debugger:
```
(gdb) bt
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f4b843e4530 in <signal handler called> () at /lib64/libc.so.6
#2  0x00007f4b7357f4ce in QSGSoftwareRenderContext::invalidate() () at /usr/lib64/libQt5Quick.so.5
#3  0x00007f4b73741c95 in QQuickRenderControlPrivate::windowDestroyed() (this=this@entry=0x557a8bd075e0)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quick/items/qquickrendercontrol.cpp:189
#4  0x00007f4b73742060 in QQuickRenderControl::~QQuickRenderControl() (this=0x557a8bd075b0, __in_chrg=<optimized out>)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quick/items/qquickrendercontrol.cpp:181
#5  0x00007f4b732505f3 in QQuickWidgetRenderControl::~QQuickWidgetRenderControl() (this=0x557a8bd075b0, __in_chrg=<optimized out>)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quickwidgets/qquickwidget.cpp:90
#6  QQuickWidgetRenderControl::~QQuickWidgetRenderControl() (this=0x557a8bd075b0, __in_chrg=<optimized out>)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quickwidgets/qquickwidget.cpp:90
#7  0x00007f4b7324e84f in QQuickWidgetPrivate::~QQuickWidgetPrivate() (this=0x557a8bd06f30, __in_chrg=<optimized out>)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quickwidgets/qquickwidget.cpp:225
#8  0x00007f4b7324e959 in QQuickWidgetPrivate::~QQuickWidgetPrivate() (this=0x557a8bd06f30, __in_chrg=<optimized out>)
    at /usr/src/debug/libqt5-qtdeclarative-5.15.1-2.1.x86_64/src/quickwidgets/qquickwidget.cpp:220
#9  0x00007f4b7ac4ae2d in  () at /usr/lib64/libQt5WebEngineWidgets.so.5
#10 0x00007f4b7436d8e5 in  () at /usr/lib64/libQt5WebEngineCore.so.5
#11 0x00007f4b74370d51 in  () at /usr/lib64/libQt5WebEngineCore.so.5
#12 0x00007f4b787a023f in  () at /usr/lib64/libQt5WebEngineCore.so.5
#13 0x0000000000000000 in  ()
```

When I add a `sip.delete(widget)` to the [tabwidget fixture](https://github.com/spyder-ide/spyder-notebook/blob/61214c7bd5e633c4ce4532049151ad1c0a89e876/spyder_notebook/widgets/tests/test_notebooktabwidget.py#L21), the above test unit terminates without segfault.

```python
@pytest.fixture
def tabwidget(mocker, qtbot):
    """Create an empty NotebookTabWidget which does not start up servers."""
    def fake_get_server(filename, start):
        return collections.defaultdict(
            str, filename=filename, notebook_dir=osp.dirname(filename))
    fake_server_manager = mocker.Mock(
        spec=ServerManager, get_server=fake_get_server)
    widget = NotebookTabWidget(None, fake_server_manager)
    qtbot.addWidget(widget)
    yield widget
    sip.delete(widget)
```

What could cause qtbot not to destroy the registered widget?

**Comment by The-Compiler** [comment]
Works fine in my project as far as I know - do you have a minimal, isolated example?

**Comment by bnavigator** [comment]
Hi,

is was about to create a minimal example working my way down from NotebookTabWidget, but the segfault does not happen anymore.

Thanks anyway!
