### ISSUE TITLE
Testing thread-spawning object crashes or hangs forever

### ISSUE THREAD

**Issue by jacopoabramo** [pytest-dev/pytest-qt#500]
I'm currently doing a refactor of a piece of code of a project; the code creates a recording object that spawns a series of threads to record data from a mock object. 

The code under test is the following:

```python

# code contained in the RecordingManager class
# it's still a w.i.p so some variables passed to startRecording are not used yet

    def startRecording(self, 
                       detectorNames: List[str], 
                       recMode: RecMode, 
                       savename: str, 
                       saveMode: SaveMode, 
                       attrs: Dict[str, str],
                       saveFormat: SaveFormat = SaveFormat.HDF5, 
                       singleMultiDetectorFile: bool = False, 
                       singleLapseFile: bool = False,
                       recFrames: int = None, 
                       recTime: float = None):
        """ Starts a recording with the specified detectors, recording mode,
        file name prefix and attributes to save to the recording per detector.
        In SpecFrames mode, recFrames (the number of frames) must be specified,
        and in SpecTime mode, recTime (the recording time in seconds) must be
        specified. """

        self.__logger.info(f'Starting recording. Mode: {recMode.name}, save mode: {saveMode.name}, save format: {saveFormat.name}')
        
        self.__totalThreads = len(detectorNames)
        self.__threadCount = 0

        virtualFiles, filePaths = self.getFiles(savename, detectorNames, recMode, saveMode, saveFormat)
        recOptions = dict(totalFrames=recFrames, totalTime=recTime)

        self.__storersList = [self.__storerMap[saveFormat](path, dest, self.detectorsManager[detectorName]) 
                              for path, dest, detectorName in zip(list(filePaths.values()), list(virtualFiles.values()), detectorNames)]
        self.__storerThreads = [Thread() for _ in range(self.__totalThreads)]

        for channel, storer, thread in zip(detectorNames, self.__storersList , self.__storerThreads):
            storer.sigMemRecAvailable.connect(self.sigMemoryRecordingAvailable.emit)
            thread.started.connect(lambda: storer.stream(recMode, saveMode, attrs[channel], **recOptions))
            thread.finished.connect(lambda: self._closeThread(storer, thread))
            storer.moveToThread(thread)
        
        if recMode in [RecMode.SpecFrames, RecMode.ScanLapse]:
            for storer in self.__storersList:
                storer.frameNumberUpdate.connect(self._updateFramesCounter)
        elif recMode == RecMode.SpecTime:
            for storer in self.__storersList:
                storer.timeUpdate.connect(self._updateSecondsCounter)
        
        for storer, thread in zip(self.__storersList, self.__storerThreads):
            thread.finished.connect(
                lambda: self._closeThread(storer, thread)
            )

        self.__record = True
        self.__wasLiveActive = len(self.__detectorsManager._activeAcqLVHandles) == 1
        
        if self.__wasLiveActive:
            # we have to temporarely interrupt the live view, as for very fast acquisitions
            # the frames captured by the live thread will create gaps in the
            # video recording; having contigous recordings is necessary for applications
            # requiring specific timestamps
            self.__oldLiveHandle = self.__detectorsManager._activeAcqLVHandles[0]
            self.__detectorsManager.stopAcquisition(self.__oldLiveHandle, liveView=True)
        
        self.__recordingHandle = self.__detectorsManager.startAcquisition()
        self.sigRecordingStarted.emit()
        
        for thread in self.__storerThreads:
            thread.start()
```

The relevant parts here are related to the `self.__storerThreads` objects, which I believe are causing the issues.

The unit test code is shown below:

```python
def record(qtbot: QtBot, detectorInfos, *args, **kwargs):
    detectorsManager = DetectorsManager(detectorInfos, updatePeriod=100)
    recordingManager = RecordingManager(detectorsManager)
    recordFinished = False

    filePerDetector, savedToDiskPerDetector = {}, {}

    def memoryRecordingAvailable(_, file, __, savedToDisk, detectorName):
        nonlocal filePerDetector, savedToDiskPerDetector
        filePerDetector[detectorName], savedToDiskPerDetector[detectorName] = file, savedToDisk
        return True

    # expected detector signals
    expectedSignals = [recordingManager.sigMemoryRecordingAvailable for _ in detectorInfos]
    expectedCallBacks = [(lambda *args, detectorName=detectorName, **kwargs: 
                        memoryRecordingAvailable(*args, detectorName=detectorName, **kwargs))
                        for detectorName in detectorInfos]

    # expected manager signals
    expectedSignals.append(recordingManager.sigRecordingEnded)
    expectedCallBacks.append(None) # signal is emitted with no value

    with qtbot.waitSignals(
            expectedSignals,
            check_params_cbs=expectedCallBacks,
            order = 'strict',
            timeout=30000
    ):
        recordingManager.startRecording(*args, **kwargs)

    return filePerDetector, savedToDiskPerDetector


@pytest.mark.parametrize('detectorInfos,numFrames',
                         [(detectorInfosBasic, 10), (detectorInfosNonSquare, 53)])
def test_recording_spec_frames(qtbot, detectorInfos, numFrames):
    filePerDetector, savedToDiskPerDetector = record(
        qtbot,
        detectorInfos,
        detectorNames=list(detectorInfos.keys()),
        recMode=RecMode.SpecFrames,
        savename='test_spec_frames',
        saveMode=SaveMode.RAM,
        attrs={detectorName: {
            'testAttr1': 2,
            'testAttr2': 'value'
        } for detectorName in detectorInfos.keys()},
        recFrames=numFrames
    )

    assert filePerDetector.keys() == detectorInfos.keys()
    assert savedToDiskPerDetector.keys() == detectorInfos.keys()
```

When launching the test, this is what I get from the traceback:

```
FAILED imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_frames[detectorInfos0-10] - pytestqt.exceptions.TimeoutError: Emitted signals: None. Missing: [sigMemoryRecordingAvailable(QString,PyQt_PyObject,PyQt_PyObject,bool) (callback: <lambda>), sigRecordingEnded()]
FAILED imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_frames[detectorInfos1-53] - pytestqt.exceptions.TimeoutError: Emitted signals: None. Missing: [sigMemoryRecordingAvailable(QString,PyQt_PyObject,PyQt_PyObject,bool) (callback: <lambda>), sigRecordingEnded()]

Exception ignored in: <function RecordingManager.__del__ at 0x000001DDC1775A60>
Traceback (most recent call last):
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\RecordingManager.py", line 97, in __del__
    self.endRecording(emitSignal=False, wait=True)
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\RecordingManager.py", line 250, in endRecording
    self.__detectorsManager.stopAcquisition(self.__recordingHandle)
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\DetectorsManager.py", line 154, in stopAcquisition
    self.sigAcquisitionStopped.emit()
RuntimeError: wrapped C/C++ object of type DetectorsManager has been deleted
Exception ignored in: <function RecordingManager.__del__ at 0x000001DDC1775A60>
Traceback (most recent call last):
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\RecordingManager.py", line 97, in __del__
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\RecordingManager.py", line 250, in endRecording
  File "C:\git\ImSwitch\imswitch\imcontrol\model\managers\DetectorsManager.py", line 154, in stopAcquisition
RuntimeError: wrapped C/C++ object of type DetectorsManager has been deleted
```

I'm not familiar with how the qtbot works but as far as I've understood the bot waits until the signals are received, otherwise after `timeout` milliseconds the test fails.

Since this test failed I tried hacking changing it as follows:

```python
def record(qtbot: QtBot, detectorInfos, *args, **kwargs):
    detectorsManager = DetectorsManager(detectorInfos, updatePeriod=100)
    recordingManager = RecordingManager(detectorsManager)
    recordFinished = False

    filePerDetector, savedToDiskPerDetector = {}, {}

    def endRecording():
        nonlocal recordFinished
        recordFinished = True

    def memoryRecordingAvailable(_, file, __, savedToDisk, detectorName):
        nonlocal filePerDetector, savedToDiskPerDetector
        filePerDetector[detectorName], savedToDiskPerDetector[detectorName] = file, savedToDisk
        return True

    # expected detector signals
    expectedSignals = [recordingManager.sigMemoryRecordingAvailable for _ in detectorInfos]
    expectedCallBacks = [(lambda *args, detectorName=detectorName, **kwargs: 
                        memoryRecordingAvailable(*args, detectorName=detectorName, **kwargs))
                        for detectorName in detectorInfos]
    
    # expected manager signals
    expectedSignals.append(recordingManager.sigRecordingEnded)
    expectedCallBacks.append(None) # signal is emitted with no value

    recordingManager.sigRecordingEnded.connect(endRecording)

    with qtbot.waitSignals(
            expectedSignals,
            check_params_cbs=expectedCallBacks,
            order = 'strict',
            timeout=30000
    ):
        recordingManager.startRecording(*args, **kwargs)
        while not recordFinished:
            qtbot.wait(100)

    return filePerDetector, savedToDiskPerDetector
```

This hangs the test forever instead (I'm assuming because the `recordFinished` flag is never set to `True` but I cannot understand why).

I tested this code in the past with a real implementation and it worked fine, so I don't exactly know what's going on here. Am I doing something wrong on the unit test side?

**Comment by jacopoabramo** [comment]
Nevermind, the code under test was bugged as hell and didn't notice until I started having a proper look.
