### ISSUE TITLE
Noisy output for exceptions in virtual methods

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#77]
When there's an exception in a virtual method, e.g. with this code:

```python
from PyQt5.QtCore import QTimer

def foo():
    raise Exception


def test_foo(qtbot):
    timer = QTimer()
    timer.setSingleShot(True)
    timer.setInterval(100)
    timer.timeout.connect(foo)
    with qtbot.waitSignal(timer.timeout):
        timer.start()
```

the output is quite noisy:

```
=========================================================================== ERRORS ===========================================================================
_______________________________________________________________ ERROR at teardown of test_foo ________________________________________________________________

self = <_pytest.runner.SetupState object at 0x7ffa51cd5cf8>, colitem = <Function 'test_foo'>

    def _callfinalizers(self, colitem):
        finalizers = self._finalizers.pop(colitem, None)
        exc = None
        while finalizers:
            fin = finalizers.pop()
            try:
>               fin()

.tox/unittests/lib/python3.4/site-packages/_pytest/runner.py:356: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/unittests/lib/python3.4/site-packages/_pytest/python.py:1868: in finish
    func()
.tox/unittests/lib/python3.4/site-packages/_pytest/python.py:1826: in teardown
    next()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

qapp = <PyQt5.QtWidgets.QApplication object at 0x7ffa51cca708>, request = <SubRequest 'qtbot' for <Function 'test_foo'>>

    @pytest.yield_fixture
    def qtbot(qapp, request):
        """
        Fixture used to create a QtBot instance for using during testing.
    
        Make sure to call addWidget for each top-level widget you create to ensure
        that they are properly closed after the test ends.
        """
        result = QtBot()
        no_capture = _exception_capture_disabled(request.node)
        if no_capture:
            yield result  # pragma: no cover
        else:
            with capture_exceptions() as exceptions:
                yield result
            if exceptions:
>               pytest.fail(format_captured_exceptions(exceptions))
E               Failed: Qt exceptions in virtual methods:
E               ________________________________________________________________________________
E                 File "/home/florian/proj/qutebrowser/git/test_foo.py", line 4, in foo
E                   raise Exception
E               
E               Exception: 
E               ________________________________________________________________________________

.tox/unittests/lib/python3.4/site-packages/pytestqt/plugin.py:554: Failed
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/test_foo.py", line 4, in foo
    raise Exception
Exception
============================================================= 1 passed, 1 error in 0.53 seconds ==============================================================
```

- Exception text is duplicated in the captured stderr output as `sys.__excepthook__` gets called which prints in there.
- The source code of `qtbot` and internal pytest source is displayed.

Can some of this be shortened, e.g. by not calling `sys.__excepthook__`, using `pytest.fail(..., pytrace=False)` or using `__tracebackhide__` somewhere?

**Comment by nicoddemus** [comment]
I think I tried using `__tracebackhide__` during `capture_exceptions()` handling but if I remember correctly it generated an exception in `py` (I will have to try again to refresh my memory).

I have thought about this before, and I think the proper solution would be to actually implement some logic in `pytest_runtest_makereport` to add that exceptions have been captured and fail the test... I will take a look at it. :smile:

**Comment by The-Compiler** [comment]
From reading the docs it looks like the `pytrace=False` argument would do exactly what we want, but I didn't actually try yet.

**Comment by nicoddemus** [comment]
Wow, I didn't even knew that parameter!

Tested it now and this is what I get:

```
============================= test session starts =============================
platform win32 -- Python 2.7.7 -- py-1.4.26 -- pytest-2.7.0
qt-api: pyqt4
session-tmp-dir: x:\tmp\session-tmp-dir-1
rootdir: x:\, inifile:
plugins: cache, timeout, localserver, xdist, cov, mock, qt
collected 1 items

test_foo.py .E

=================================== ERRORS ====================================
________________________ ERROR at teardown of test_foo ________________________
Qt exceptions in virtual methods:
________________________________________________________________________________
  File "x:\test_foo.py", line 4, in foo
    raise Exception

Exception:
________________________________________________________________________________

---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "x:\test_foo.py", line 4, in foo
    raise Exception
Exception
====================== 1 passed, 1 error in 0.13 seconds ======================
```

I would say that's a lot better already. :smile:

**Comment by nicoddemus** [comment]
Using a slightly modified example to have more frames in the traceback:

```python
from PyQt4.QtCore import QTimer

def foo():
    raise Exception

def bar():
    foo()

def test_foo(qtbot):
    timer = QTimer()
    timer.setSingleShot(True)
    timer.setInterval(100)
    timer.timeout.connect(bar)
    with qtbot.waitSignal(timer.timeout):
        timer.start()
 
```

Gives:

```
============================= test session starts =============================
platform win32 -- Python 2.7.7 -- py-1.4.26 -- pytest-2.7.0
qt-api: pyqt4
session-tmp-dir: x:\tmp\session-tmp-dir-2
rootdir: x:\, inifile:
plugins: cache, timeout, localserver, xdist, cov, mock, qt
collected 1 items

test_foo.py .E

=================================== ERRORS ====================================
________________________ ERROR at teardown of test_foo ________________________
Qt exceptions in virtual methods:
________________________________________________________________________________
  File "x:\test_foo.py", line 8, in bar
    foo()
  File "x:\test_foo.py", line 4, in foo
    raise Exception

Exception:
________________________________________________________________________________

---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "x:\test_foo.py", line 8, in bar
    foo()
  File "x:\test_foo.py", line 4, in foo
    raise Exception
Exception
====================== 1 passed, 1 error in 0.13 seconds ======================
```

**Comment by The-Compiler** [comment]
Nice, definitely a lot better! What about not calling `sys.__excepthook__` so the stderr capture is gone? I don't think calling that does anything other than printing it to stderr, but I'll check.
